# Generated by Django 4.2.7 on 2024-04-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='answers',
            field=models.JSONField(default=list),
        ),
    ]
