# Generated by Django 4.2.7 on 2024-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quizquestion_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('sentence', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
    ]
