# Generated by Django 4.2.7 on 2024-04-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wordofday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='TopWord',
        ),
    ]
