import NavBar from "../components/NavBar";

const PrivacyPage = () => {
    return (
        <div>
            <NavBar logoHide={false} />
            <div style={{margin:"3vw 8vw 5vw 5vw"}}>
                <h2 style={{fontSize:"5vh", fontWeight:"700"}}>Privacy Policy for WordWise Dictionary Web App</h2>
                <p style={{fontSize:"3vh", marginTop:"3vh"}}><strong>Effective Date:</strong> 10/04/2024</p>
                <p style={{marginTop:"2vh"}}>Thank you for choosing WordWise, a sophisticated dictionary web application with advanced AI suggestion capabilities. Safeguarding your privacy and ensuring the security of your personal information is a fundamental priority for us. This Privacy Policy elucidates how we collect, use, disclose, and safeguard your information when you engage with our web application.</p>

                <h3 style={{fontSize:"3vh", fontWeight:"600", marginTop:"3vh"}}>1. Information We Collect</h3>
                <p style={{marginTop:"1.5vh"}}>
                    <strong>a. Personal Information:</strong> <br />
                    Upon your voluntary submission, we may collect personal information such as your name, email address, and any additional details you provide when contacting us or creating an account.
                </p>
                <p style={{marginTop:"1.5vh"}}>
                    <strong>b. Usage Information:</strong> <br />
                    We automatically gather certain information about your device and interactions with our web application, including but not limited to your IP address, browser type, operating system, pages visited, and other relevant usage statistics.
                </p>
                <p style={{marginTop:"1.5vh"}}>
                    <strong>c. AI Suggestion Data:</strong> <br />
                    When utilizing our AI suggestion feature, we may gather and retain the text input and suggestions generated by the AI to refine our services and enhance your user experience.
                </p>

                <h3 style={{fontSize:"3vh", fontWeight:"600", marginTop:"3vh"}}>2. How We Use Your Information</h3>
                <p style={{marginTop:"1.5vh"}}>We employ the information collected for various purposes, including but not limited to:</p>
                <ul style={{marginTop:"1.5vh"}}>
                    <li>Facilitating, maintaining, and improving WordWise and its functionalities.</li>
                    <li>Addressing your inquiries, feedback, and support requests promptly and effectively.</li>
                    <li>Communicating with you regarding updates, announcements, and other pertinent information related to our services.</li>
                    <li>Analyzing usage patterns and preferences to optimize user experience and refine our offerings.</li>
                </ul>

                <h3  style={{fontSize:"3vh", fontWeight:"600", marginTop:"3vh"}}>3. How We Share Your Information</h3>
                <p style={{marginTop:"1.5vh"}}>We hold your privacy in the highest regard and do not engage in selling, trading, or renting your personal information to third parties. However, we may share your information under the following circumstances:</p>
                <ul style={{marginTop:"1.5vh"}}>
                    <li>With your explicit consent or as necessary to fulfill any purpose disclosed at the time of collection.</li>
                    <li>With trusted third-party service providers who assist us in operating our web application and delivering services to you.</li>
                    <li>When compelled by law or to safeguard our rights, property, or safety, or those of others.</li>
                </ul>

                <h3 style={{fontSize:"3vh", fontWeight:"600", marginTop:"3vh"}}>4. Data Security</h3>
                <p style={{marginTop:"1.5vh"}}>We implement reasonable measures to safeguard your information from unauthorized access, alteration, disclosure, or destruction. Nonetheless, it's important to acknowledge that no method of transmission over the internet or electronic storage is entirely secure, and we cannot guarantee absolute security.</p>

                <h3 style={{fontSize:"3vh", fontWeight:"600", marginTop:"3vh"}}>5. Children’s Privacy</h3>
                <p style={{marginTop:"1.5vh"}}>WordWise is not directed at individuals under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and suspect that your child has provided us with personal information, please contact us, and we will take appropriate steps to rectify the situation.</p>

                <h3 style={{fontSize:"3vh", fontWeight:"600", marginTop:"3vh"}}>6. Changes to this Privacy Policy</h3>
                <p style={{marginTop:"1.5vh"}}>We reserve the right to modify or update this Privacy Policy at our discretion without prior notice. We encourage you to periodically review this Privacy Policy for any changes. Your continued use of WordWise following the posting of modifications constitutes acceptance of those changes.</p>

                <h3 style={{fontSize:"3vh", fontWeight:"600", marginTop:"3vh"}}>7. Contact Us</h3>
                <p style={{marginTop:"1.5vh"}}>Should you have any questions, concerns, or feedback regarding this Privacy Policy or our information handling practices, please don't hesitate to reach out to us at support@wordwise.com.</p>

            </div>
        </div>
    );
}

            export default PrivacyPage;